# Generated by Django 3.2.7 on 2021-10-08 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
